# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: jenkins-service
  namespace: keptn
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            # Disable scale to zero with a minScale of 1.
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: keptn/jenkins-service:0.1.0
            env: 
            - name: JENKINS_URL
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: jenkinsurl
            - name: JENKINS_USER
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: user
            - name: JENKINS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: password         

# Subscription from the GcpPubSubSource's output Channel to the Knative Service below.
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: jenkins-configuration-changed-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: configuration-changed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: jenkins-service

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: jenkins-deployment-finished-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: deployment-finished
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: jenkins-service

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: jenkins-evaluation-done-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: evaluation-done
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: jenkins-service

#---
#apiVersion: eventing.knative.dev/v1alpha1
#kind: Subscription
#metadata:
#  name: jenkins-tests-finished-subscription
#  namespace: keptn
#spec:
#  channel:
#    apiVersion: eventing.knative.dev/v1alpha1
#    kind: Channel
#    name: tests-finished
#  subscriber:
#    ref:
#      apiVersion: serving.knative.dev/v1alpha1
#      kind: Service
#      name: jenkins-service
